### ISSUE TITLE
konlpy 제공 함수명과 동일한 함수명 제공

### ISSUE THREAD

**Issue by 9bow** [shineware/PyKOMORAN#16]
## 기능 설명
konlpy 이용에 익숙한 사용자를 위해 konlpy에서 제공하는 함수명을 alias로 함께 제공합니다.

## 추가 정보
[konlpy Komoran Class](http://konlpy.org/en/latest/api/konlpy.tag/)

```
morphs(phrase)¶
Parse phrase to morphemes.

nouns(phrase)
Noun extractor.

pos(phrase, flatten=True, join=False)
POS tagger.
```

**Comment by gamamoe** [comment]
좋은 아이디어네요!
