### ISSUE TITLE
사용자 사전 적용 문제

### ISSUE THREAD

**Issue by wlsdudqo97** [shineware/PyKOMORAN#49]
## 문제 설명
'최순실'을 명사로 분석하기 위해 사용자 사전을 추가하여 적용시켜보았지만 최순/NNP, 실/NNP로 분석합니다 . IDE는 파이참 2019.1 을 사용하였고 파이썬 3.7 버전을 사용하고있습니다.

## 재현 경로
파이참 프로젝트 안에 dic 디렉토리를 만든 뒤 dic.user라는 user파일을 추가해주었습니다.
dic.user 파일의 내용은 다음과 같습니다.

# dic.user
최순실	NNP

# 코드
from PyKomoran import *

komoran = Komoran(DEFAULT_MODEL['FULL'])
komoran.set_user_dic('dic/dic.user')
s = komoran.get_list('최순실씨가 민주주의를 외칠 때')
print(s)

이렇게 komoran 객체를 생성한 뒤 사용자 사전을 적용시키고 형태소 분석을 시행한 결과
[최순/NNP, 실/NNP, 씨/NNB, 가/JKS, 민주주의/NNG, 를/JKO, 외치/VV, ㄹ/ETM, 때/NNG]
위처럼 최순실이 아닌 최순/실로 사용자 사전이 적용되지 않은 결과가 나옵니다. dic.user에 다른 명사를 넣어봐도 적용되지 않은  결과가 나옵니다.
혹시 사용자 사전이 있어야하는 경로가 정해져있나요?

## 기대 상황
최순/실이 아닌 최순실로 분석 되었으면 합니다.

## 환경 정보
_어떤 환경에서 이 문제가 발생하였나요?_
* OS 종류 / 버전: Window10
* PyKomoran 버전: 0.1.5
* Python 버전: 3.7
* Py4J 버전: 0.10.8.1

**Comment by gamamoe** [comment]
안녕하세요. 사용자 사전의 타겟 단어와 형태소는 tab (\t)으로 분리되어야 합니다. 아마도 white space로 분리해서 만드신 것으로 보입니다. Mac OS, PyKomoran 0.1.5, Python 3.7 버전에서 사용자 사전을 제대로 설정했을 시 올바르게 동작하는 것을 확인했습니다. @9bow 혹시 사용사 사전 설정에 대한 문서가 있었을까요?
![image](https://user-images.githubusercontent.com/9076745/57524580-32a2d700-7363-11e9-94f8-a5c67b9b0bb8.png)

**Comment by 9bow** [comment]
@dolpang2 
네, 아직 사용자 사전 / 기분석 사전 사용법 관련한 문서는 준비 중에 있습니다.

@wlsdudqo97 
안녕하세요, 다음과 같은 2가지를 확인해보시면 좋을 것 같습니다.
1. @dolpang2 님께서 위에 덧글 남겨주신 것처럼 TAB 키를 이용하여 형태소와 품사를 나누어 주셔야 합니다. (또는, 뒤에 품사를 생략하시면 자동으로 고유명사/NNP로 간주합니다.
1. 사용자 사전이 존재하는 위치의 `절대 경로`를 제공해주셔야 합니다. (예. `C:\Users\...`) 아래와 같은 코드를 사용하여 현재 위치를 얻어올 수 있습니다.
```
import os
cwd = os.getcwd()
print(cwd)
# /Users/reserve/Workspace/PyKOMORAN
```
계속 이슈가 있거나, 문제가 해결되셨다면 확인 부탁드립니다. :)

**Comment by wlsdudqo97** [comment]
답변 감사합니다.
남겨주신 답변처럼 사용자 사전의 절대경로를 넣어주었습니다. 사용자 사전에는 아래와 같이 형태소와 품사를 Tab으로 구분지었습니다.

샤인웨어	NNP
cm	SL
최순실	NNP

`from PyKomoran import *

komoran = Komoran(DEFAULT_MODEL['FULL'])

komoran.set_user_dic('/Users/wlsdu/Desktop/data_mining/dic/dic.user')
s = komoran.get_list('최순실 씨가 민주주의를 외칠 때')
print(s)`

출력:
[최순/NNP, 실/NNP, 씨/NNB, 가/JKS, 민주주의/NNG, 를/JKO, 외치/VV, ㄹ/ETM, 때/NNG]

하지만 위에서와 같이 사용자 사전이 제대로 적용되지 않은 결과가 출력되었습니다. 사용자 사전은 메모장에 내용을 적은 후 확장자 .user로 저장해주었습니다. 혹시 확장자가 .dic이어야 하나요?

**Comment by wlsdudqo97** [comment]
사용자 사전을 저장할 때 인코딩을 UTF-8로 설정하고 저장했더니 정상적으로 적용되어 문제가 해결되었습니다.
피드백 감사합니다!  :)

**Comment by 9bow** [comment]
확인 감사합니다.
사용 중에 다른 이슈 또는 개선 사항을 발견하시면 알려주세요 :D
