### ISSUE TITLE
pos 호출 시 발생하는 에러 질문드립니다.

### ISSUE THREAD

**Issue by FineSrss** [shineware/PyKOMORAN#54]
## 문제 설명
현재 docker-compose를 이용하여 nginx+gunicorn+flask를 이용하여 형태소분석용 API서버를 하나 띄웠습니다.
워커와 쓰레드를 하나 이상의 값으로 설정하고 Jmeter로 request 테스트를 해봤는데 아래와 같은 에러들이 뜹니다.
1. "pos_sentence = komoran.pos(sentence)" : 'str' object has no attribute 'get'"
2. "pos_sentence = komoran.pos(sentence)" : 'int' object has no attribute 'get'
3. "pos_sentence = komoran.pos(sentence)" : 'NoneType' object is not iterable
4. "pos_sentence = komoran.pos(sentence)" : Komoran is NOT initialized!
5. "pos_sentence = komoran.pos(sentence)" : iter() returned non-iterator of type 'str'
6. "pos_sentence = komoran.pos(sentence)" : iter() returned non-iterator of type 'NoneType'
7. "pos_sentence = komoran.pos(sentence)" : 'JavaSet' object cannot be interpreted as an integer
8. "pos_sentence = komoran.pos(sentence)"): An error occurred while calling o3041.get. Trace:
py4j.Py4JException: Method get([class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

## 재현 경로
_어떻게 하면 동일한 문제가 계속 발생하나요?_
"러너웨이는 정규시즌 4위를 기록하며 이전 시즌의 강력함을 보여주지 못했지만 플레이오프에서 난적들을 모두 꺾고 우승을 차지하며 명문 팀의 저력을 보여줬다" 이 문장을 가지고 동시에 여러 요청을 넣으면 발생합니다.
Apache Jmeter로 ThreadGroup (user : 10, period : 1s, Loop Count : 10)으로 총 100번 요청 넣었습니다.

## 기대 상황
_정상적인 상황에서는 어떻게 동작해야 한다고 생각하세요?_
 [러너웨이/NNP(0,4), 는/JX(4,5), 정규/NNP(6,8), 시즌/NNP(8,10), 4/SN(11,12), 위/NNB(12,13), 를/JKO(13,14), 기록/NNG(15,17), 하/XSV(17,18), 며/EC(18,19), 이전/NNG(20,22), 시즌/NNP(23,25), 의/JKG(25,26), 강력/XR(27,29), 하/XSA(29,30), ㅁ/ETN(29,30), 을/JKO(30,31), 보여주/VV(32,35), 지/EC(35,36), 못하/VX(37,39), 았/EP(37,39), 지만/EC(39,41), 플레이오프/NNP(42,47), 에서/JKB(47,49), 난적/NNP(50,52), 들/XSN(52,53), 을/JKO(53,54), 모두/MAG(55,57), 꺾/VV(58,59), 고/EC(59,60), 우승/NNP(61,63), 을/JKO(63,64), 차지/NNG(65,67), 하/XSV(67,68), 며/EC(68,69), 명문/NNP(70,72), 팀/NNG(73,74), 의/JKG(74,75), 저력/NNP(76,78), 을/JKO(78,79), 보이/VV(80,83), 어/EC(80,83), 주/VX(80,83), 었/EP(80,83), 다/EC(83,84)]
이런식의 형태소 분석 결과가 나와야합니다.

## 환경 정보
_어떤 환경에서 이 문제가 발생하였나요?_
* OS 종류 / 버전: Ubuntu 18.04
* PyKomoran 버전: 0.1.5
* Python 버전: 3.6.9
* Py4J 버전: 0.10.8.1

## 추가 정보
_스크린샷이나 에러 로그 등, 추가 정보가 있다면 남겨주세요._

**Comment by gamamoe** [comment]
안녕하세요. 전체 코드가 아니라도 PyKOMORAN 사용하시는 부분 코드를 올려주시면 확인이 더 빠를 것 같습니다.

**Comment by FineSrss** [comment]
> 안녕하세요. 전체 코드가 아니라도 PyKOMORAN 사용하시는 부분 코드를 올려주시면 확인이 더 빠를 것 같습니다.

```
@komoran_api.route('/', methods=['POST'])
def komoran_nlp():
    print('called komoran_nlp!!!')
    try:
        data = request.get_json()
        seqidx = data['authinit']
        channelcode = data['sentence']

        anal_sentence = parse_nlp_sentence(komoran.pos(sentence))  # 에러가 발생하는 부분

        response_code = '00'
        if length(anal_sentence) == 0:
            response_code = '99'

        return_str = start_str + '|' + response_code + '|' + authinit + '|' + anal_sentence + '|' + end_str
        return make_response(return_str)
    except Exception as e:
        exc_type, exc_obj, tb = sys.exc_info()
        f = tb.tb_frame
        lineno = tb.tb_lineno
        filename = f.f_code.co_filename
        linecache.checkcache(filename)
        line = linecache.getline(filename, lineno, f.f_globals)
        exc_str = 'EXCEPTION IN ({}, LINE {} "{}"): {}'.format(filename, lineno, line.strip(), exc_obj)
        print(exc_str)
        return make_response(exc_str)


    return make_response('999')

```





사용하는 코드는 위와 같습니다!
테스트용 API서버 구축해본거고 주석 표시된 부분(anal_sentence = parse_nlp_sentence(komoran.pos(sentence)))에서 위 에러가 모두 발생했습니다

**Comment by 9bow** [comment]
안녕하세요, @FineSrss 님.
재현 경로에서 `동시에 여러 요청을 넣으면 발생합니다.`라고 해주셨는데요,
혹시 한 건의 요청만 있는 경우에는 응답이 정상적인지요?

**Comment by FineSrss** [comment]
> 안녕하세요, @FineSrss 님.
> 재현 경로에서 `동시에 여러 요청을 넣으면 발생합니다.`라고 해주셨는데요,
> 혹시 한 건의 요청만 있는 경우에는 응답이 정상적인지요?

음.. 제가 다시 테스트해보니까 요청유저수를 1명으로 잡고 건수를 100으로 늘려도 간간히 발생하는 경우가 있습니다
>> 정정합니다, 1명으로하고 100건요청시에는 발생안하네요..

**Comment by gamamoe** [comment]
`komoran` 객체는 어디서 처음 초기화가 되는 지 궁금합니다. 스택트레이스만 봤을 때는 워커가 뜰 때 제대로 초기화가 안된 상태에서 pos를 하면서 문제가 발생하는 것 같은데요. 혹시 추가적인 정보를 더 알 수 있을까요?

**Comment by FineSrss** [comment]
> `komoran` 객체는 어디서 처음 초기화가 되는 지 궁금합니다. 스택트레이스만 봤을 때는 워커가 뜰 때 제대로 초기화가 안된 상태에서 pos를 하면서 문제가 발생하는 것 같은데요. 혹시 추가적인 정보를 더 알 수 있을까요?

komoran = Komoran("EXP")
komoran.set_fw_dic('/www/Dict2.txt')
komoran.set_user_dic('/www/testdict.txt')

@komoran_api.route('/', methods=['POST'])

이런식으로 모듈파일 상단에 선언되어 있습니다.

**Comment by gamamoe** [comment]
@FineSrss 안녕하세요. 다음 이슈와 관련있는 것으로 보입니다 ( https://github.com/shineware/PyKOMORAN/issues/48#issuecomment-504794685 ) 빠른 시일내에 수정하기 어려울 것 같습니다 ㅠ

**Comment by FineSrss** [comment]
> @FineSrss 안녕하세요. 다음 이슈와 관련있는 것으로 보입니다 ( [#48 (comment)](https://github.com/shineware/PyKOMORAN/issues/48#issuecomment-504794685) ) 빠른 시일내에 수정하기 어려울 것 같습니다 ㅠ

퍼포먼스를 최대한 향상시킬려는게 목표였는데 적당히 타협해야겠군요.. 답변 감사드립니다!
