### ISSUE TITLE
get_morphes_by_tags가 값을 반환하지 않는 문제

### ISSUE THREAD

**Issue by kes185** [shineware/PyKOMORAN#57]
## 문제 설명
안녕하세요, pykomoran을 이용하는 중 get_morphes_by_tags가 빈값을 반환하는 문제가 있는데
혼자 해결이 안되어 문의를 남깁니다.

## 재현 경로
분석하려는 문장이 무엇이든 get_morphes_by_tags()를 실행하면 결과가 뜨기까지 시간은 소요하지만
아무 값도 반환하지 않습니다.

PyKomoran을 활용한 자연어처리 뽀개기!(https://blog.shineware.co.kr/article/2019/06/04/pykomoran-usage.html)
의 코드를 그대로 복사하여 따라하던 중이었습니다.

target_tags = ['NNG','VV', 'VA']
cleansed_review_data['specific_tokens'] = cleansed_review_data['document'].map(lambda s: komoran.get_morphes_by_tags(s, tag_list=target_tags))
cleansed_review_data.sample(4)[['document', 'label', 'specific_tokens']]

실행하면

![image](https://user-images.githubusercontent.com/58378608/118077216-a2367b80-b3ee-11eb-904a-77fc16193d7b.png)

이렇게 빈값만 반환되고 아예 단일 문장으로 

str_to_analyze = "① 대한민국은 민주공화국이다. ② 대한민국의 주권은 국민에게 있고, 모든 권력은 국민으로부터 나온다."
komoran.get_morphes_by_tags(str_to_analyze, tag_list=['NNP', 'NNG', 'SF'])

실행해봐도 [] 이렇게 반환됩니다
모델패스를 바꿔가며 해봤는데도 동일하였습니다

## 기대 상황
명사, 동사, 형용사가 반환되어야 할텐데ㅜㅜㅜ

## 환경 정보
* OS 종류 / 버전: windows 10 pro 
* PyKomoran 버전: 0.1.5
* Python 버전: 3.8.5
* Py4J 버전: 0.10.8.1

## 추가 정보
get_plain_text만 잘 작동되고 get_nouns 등의 메소드도 작동하지 않습니다..ㅜ
무엇이 잘못된 것일까요 도움의 말씀 부탁드립니다

**Comment by kes185** [comment]
제 환경이 문제였던 거 같습니다, 다른 노트북으로 바꿔서 하니 되네요ㅜ

**Comment by 9bow** [comment]
잘 해결되셨다니 다행입니다. ^^

**Comment by kes185** [comment]
항상 잘 사용하고 있습니다! 좋은 패키지 배포해주셔서 정말 감사드려요!!
